### ISSUE TITLE
Cloning private repositories require authentication

### ISSUE THREAD

**Issue by theishanbh** [automation-co/borzoi#22] opened 2022-04-28 10:56 UTC
When using `borzoi clone` command on private repositories, it requires you to have authentication. Authentication needs to be added.

![image](https://user-images.githubusercontent.com/91272949/165737571-6777a465-cd16-488c-8789-5295636d5ab0.png)

**Comment by Aarush-Goyal** [comment] 2022-04-28 16:05
Duplicate of #2

**Closed by Aarush-Goyal** 2022-04-28 16:05 UTC
